#install.packages("readxl")
# if(!require("devtools")) {
#   install.packages("devtools")
#   library("devtools")
# }

# library("devtools")
# devtools::install_github("mdscheuerell/muti")
library("readxl")
# library(muti)
install.packages("caret")
install.packages("klaR")
library(caret)
library(klaR)

data <- read_excel("Integrated Data.xlsx")
attach(data)
# muti(data$`Stomach ache history`,data$IgM)
cor.test(data$`Stomach ache history`,IgM)
cor.test(data$`Stomach ache history`,data$IgA)
cor.test(data$`Stomach ache history`,data$IgG)
cor.test(data$Diabet,data$IgM)
cor.test(data$Diabet,data$IgA)
cor.test(data$Diabet,data$IgG)

l =lm(Helicobacte~ Diabet, data= data)
summary(l)
plot(Helicobacte~ Diabet)
abline(lm)
?abline()
confusionMatrix(Helicobacte, Diabet, data = data)
sum(Diabet  ==Helicobacte) 
